### ISSUE TITLE
Docker image in the hub.docker.com is outdated

### ISSUE THREAD

**Issue by maxkoryukov** [dencold/pgcli-docker#3]
Hello!

The image on the [Docker Hub](https://hub.docker.com/r/dencold/pgcli/tags/) is old, and the updates from the latest commits are not there.

Please, update the image in the public docker-registry.

Thank you for this image!

**Comment by dencold** [comment]
Hi @maxkoryukov this should be addressed now. I've updated the `Dockerfile` and pushed the latest image to Docker Hub. I no longer pin the version in the image, so when you pull from Docker it will automatically grab the latest version of `pgcli`. Hope that helps. Thanks for adding the issue.
